export default {
  TYPE: {
    SIMPLE_TEXT: 'SIMPLE_TEXT',
    SIMPLE_IMAGE: 'SIMPLE_IMAGE',
    BASIC_CARD: 'BASIC_CARD',
    COMMERCE_CARD: 'COMMERCE_CARD',
    LIST_CARD: 'LIST_CARD',
    CAROUSEL: 'CAROUSEL'
  }
}